name: Generate Game Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    
    - name: Generate Game Pages
      run: node generate-game-pages.js
    
    - name: Commit and Push Generated Files
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add games/*.html
        git commit -m "Auto-generate game pages" || echo "No changes to commit"
        git push
